---
git:
  branch: master
triggers:
  cron: "@daily"
clean_workspace: true
script:
  - echo "Build SUNET Custom ARGUS-Fronted Image"
builders:
  - docker
docker_name: sunet/argus-frontend
docker_tags:
  - "v1.8.1_sunetbuild"
